#include <stdio.h>
#include "ft_printf.h"

int	main()
{
	int		counter_test;
	int		counter_oficial;
	char	*ptr;
	char	*ptr_null;

	ptr = "This";
	ptr_null = NULL;

	printf("=======[BASIC FUNCTIONALITIES]=======\n\n");
	counter_test = 0;
	counter_oficial = 0;
	printf("=======[ft_print_p]=======\n\n");
	counter_test += ft_printf("This %%p: %p\n", ptr);
	counter_oficial += printf("This %%p: %p\n", ptr);
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);

	printf("=======[ft_print_s]=======\n\n");
	counter_test += ft_printf("This %%s: %s\n", ptr);
	counter_oficial += printf("This %%s: %s\n", ptr);
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	
	counter_test += ft_printf("This %%s: %s\n", ptr_null);
	counter_oficial += printf("This %%s: %s\n", ptr_null);
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	
	printf("=======[ft_print_c]=======\n\n");
	counter_test += ft_printf("This %%c: %c\n", 'c');
	counter_oficial += printf("This %%c: %c\n", 'c');
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);

	printf("=======[ft_print_int]=======\n\n");
	counter_test += ft_printf("This %%i: %i\n", 59845);
	counter_oficial += printf("This %%i: %i\n", 59845);
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%i: %i\n", -2984655);
	counter_oficial += printf("This %%i: %i\n", -2984655);
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);

	printf("=======[ft_print_u]=======\n\n");
	counter_test += ft_printf("This %%u: %u\n", 2984655);
	counter_oficial += printf("This %%u: %u\n", 2984655);
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%u: %u\n", 12984655);
	counter_oficial += printf("This %%u: %u\n", 12984655);
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%u: %u\n", 0);
	counter_oficial += (printf("This %%u: %u\n", 0));
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%u: %u\n", -1);
	counter_oficial += (printf("This %%u: %u\n", -1));
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%u: %u\n", 1);
	counter_oficial += (printf("This %%u: %u\n", 1));
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%u: %u\n", 9);
	counter_oficial += (printf("This %%u: %u\n", 9));
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%u: %u\n", 10);
	counter_oficial += (printf("This %%u: %u\n", 10));
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%u: %u\n", 11);
	counter_oficial += (printf("This %%u: %u\n", 11));
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%u: %u\n", 15);
	counter_oficial += (printf("This %%u: %u\n", 15));
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%u: %u\n", 16);
	counter_oficial += (printf("This %%u: %u\n", 16));
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%u: %u\n", 17);
	counter_oficial += (printf("This %%u: %u\n", 17));
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%u: %u\n", 99);
	counter_oficial += (printf("This %%u: %u\n", 99));
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%u: %u\n", 100);
	counter_oficial += (printf("This %%u: %u\n", 100));
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%u: %u\n", 101);
	counter_oficial += (printf("This %%u: %u\n", 101));
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%u: %u\n", -9);
	counter_oficial += (printf("This %%u: %u\n", -9));
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%u: %u\n", -10);
	counter_oficial += (printf("This %%u: %u\n", -10));
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%u: %u\n", -11);
	counter_oficial += (printf("This %%u: %u\n", -11));
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%u: %u\n", -14);
	counter_oficial += (printf("This %%u: %u\n", -14));
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%u: %u\n", -15);
	counter_oficial += (printf("This %%u: %u\n", -15));
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%u: %u\n", -16);
	counter_oficial += (printf("This %%u: %u\n", -16));
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%u: %u\n", -99);
	counter_oficial += (printf("This %%u: %u\n", -99));
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%u: %u\n", -100);
	counter_oficial += (printf("This %%u: %u\n", -100));
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%u: %u\n", -101);
	counter_oficial += (printf("This %%u: %u\n", -101));
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%u: %u\n", INT_MAX);
	counter_oficial += (printf("This %%u: %u\n", INT_MAX));
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%u: %u\n", INT_MIN);
	counter_oficial += (printf("This %%u: %u\n", INT_MIN));
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%u: %u\n", LONG_MAX);
	counter_oficial += (printf("This %%u: %u\n", LONG_MAX));
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%u: %u\n", LONG_MIN);
	counter_oficial += (printf("This %%u: %u\n", LONG_MIN));
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%u: %u\n", UINT_MAX);
	counter_oficial += (printf("This %%u: %u\n", UINT_MAX));
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%u: %u\n", ULONG_MAX);
	counter_oficial += (printf("This %%u: %u\n", ULONG_MAX));
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%u: %u\n", 9223372036854775807LL);
	counter_oficial += (printf("This %%u: %u\n", 9223372036854775807LL));
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	
	printf("=======[ft_print_x]=======\n\n");
	counter_test += ft_printf("This %%x: %x\n", 2984655);
	counter_oficial += printf("This %%x: %x\n", 2984655);
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	
	printf("=======[ft_print_X]=======\n\n");
	counter_test += ft_printf("This %%X: %X\n", 2984655);
	counter_oficial += printf("This %%X: %X\n", 2984655);
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);

	printf("=======[WITH -0.* FLAGS]=======\n\n");
	printf("=======[ft_print_c]=======\n\n");
	counter_test += ft_printf("This %%25c: %25c\n", 'c');
	counter_oficial += printf("This %%25c: %25c\n", 'c');
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%-5c: %-5c\n", 'c');
	counter_oficial += printf("This %%-5c: %-5c\n", 'c');
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);

	printf("=======[ft_print_s]=======\n\n");
	counter_test += ft_printf("This %%5s: %5s\n", "This");
	counter_oficial += printf("This %%5s: %5s\n", "This");
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%5s: %5s\n", "Another string");
	counter_oficial += printf("This %%5s: %5s\n", "Another string");
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%-5s: %-5s\n", "This");
	counter_oficial += printf("This %%-5s: %-5s\n", "This");
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%-5s: %-5s\n", "Another string");
	counter_oficial += printf("This %%-5s: %-5s\n", "Another string");
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%-*s: %-*s\n", 25, "Another string");
	counter_oficial += printf("This %%-*s: %-*s\n", 25, "Another string");
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%.s: %.s\n", "-");
	counter_oficial += printf("This %%.s: %.s\n", "-");
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += (ft_printf("This %%.s: %.1s %.2s %.3s %.4s\n", " - ", "", "4", ""));
	counter_oficial += (printf("This %%.s: %.1s %.2s %.3s %.4s\n", " - ", "", "4", ""));
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += (ft_printf("This %%.s: %.2s %.3s %.4s %.5s %.1s\n", " - ", "", "4", "", "2 "));
	counter_oficial += (printf("This %%.s: %.2s %.3s %.4s %.5s %.1s\n", " - ", "", "4", "", "2 "));
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);



	printf("=======[ft_print_int]=======\n\n");
	counter_test += ft_printf("This %%25d: %25d\n", 257);
	counter_oficial += printf("This %%25d: %25d\n", 257);
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%.25d: %.25d\n", 257);
	counter_oficial += printf("This %%.25d: %.25d\n", 257);
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%025d: %025d\n", 257);
	counter_oficial += printf("This %%025d: %025d\n", 257);
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%.25d: %.25d\n", -257);
	counter_oficial += printf("This %%.25d: %.25d\n", -257);
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%025d: %025d\n", -257);
	counter_oficial += printf("This %%025d: %025d\n", -257);
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %% 010d: % 010d\n", 257);
	counter_oficial += printf("This %% 010d: % 010d\n", 257);
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%+010d: %+010d\n", 257);
	counter_oficial += printf("This %%+010d: %+010d\n", 257);
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %% 010d: % 010d\n", -257);
	counter_oficial += printf("This %% 010d: % 010d\n", -257);
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%+010d: %+010d\n", -257);
	counter_oficial += printf("This %%+010d: %+010d\n", -257);
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%5d: %5d\n", 2578787);
	counter_oficial += printf("This %%5d: %5d\n", 2578787);
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%5.d: %5.d\n", 0);
	counter_oficial += printf("This %%5.d: %5.d\n", 0);
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%6.5d: %6.5d\n", 123);
	counter_oficial += printf("This %%6.5d: %6.5d\n", 123);
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%-5d: %-5d\n", 257);
	counter_oficial += printf("This %%-5d: %-5d\n", 257);
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%-5d: %-5d\n", 2578787);
	counter_oficial += printf("This %%-5d: %-5d\n", 2578787);
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%05d: %05d\n", 257);
	counter_oficial += printf("This %%05d: %05d\n", 257);
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%05d: %05d\n", 2578787);
	counter_oficial += printf("This %%05d: %05d\n", 2578787);
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);

	printf("=======[ft_print_p]=======\n\n");
	counter_test += ft_printf("This %%25p: %25p\n", ptr);
	counter_oficial += printf("This %%25p: %25p\n", ptr);
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%5p: %5p\n", ptr);
	counter_oficial += printf("This %%5p: %5p\n", ptr);
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%-25p: %-25p\n", ptr);
	counter_oficial += printf("This %%-25p: %-25p\n", ptr);
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%-5p: %-5p\n", ptr);
	counter_oficial += printf("This %%-5p: %-5p\n", ptr);
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);

	printf("=======[ft_print_u]=======\n\n");
	counter_test += ft_printf("This %%25u: %25u\n", 213548);
	counter_oficial += printf("This %%25u: %25u\n", 213548);
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%5u: %5u\n", 213548);
	counter_oficial += printf("This %%5u: %5u\n", 213548);
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%-25u: %-25u\n", 213548);
	counter_oficial += printf("This %%-25u: %-25u\n", 213548);
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%-5u: %-5u\n", 213548);
	counter_oficial += printf("This %%-5u: %-5u\n", 213548);
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);

	printf("=======[ft_print_x]=======\n\n");
	counter_test += ft_printf("This %%25x: %25x\n", 21354489);
	counter_oficial += printf("This %%25x: %25x\n", 21354489);
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%025x: %025x\n", 21354489);
	counter_oficial += printf("This %%025x: %025x\n", 21354489);
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%5x: %5x\n", 21354489);
	counter_oficial += printf("This %%5x: %5x\n", 21354489);
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%.5x: %.5x\n", 21354489);
	counter_oficial += printf("This %%.5x: %.5x\n", 21354489);
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%10.5x: %10.5x\n", 21354489);
	counter_oficial += printf("This %%10.5x: %10.5x\n", 21354489);
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%10.8x: %10.8x\n", 21354489);
	counter_oficial += printf("This %%10.8x: %10.8x\n", 21354489);
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%.x: %.x\n", 0);
	counter_oficial += printf("This %%.x: %.x\n", 0);
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%-25x: %-25x\n", 21354489);
	counter_oficial += printf("This %%-25x: %-25x\n", 21354489);
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%-5x: %-5x\n", 21354489);
	counter_oficial += printf("This %%-5x: %-5x\n", 21354489);
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%#x: %#x\n", 21354489);
	counter_oficial += printf("This %%#x: %#x\n", 21354489);
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%#13.10x: %#13.10x\n", 21354489);
	counter_oficial += printf("This %%#13.10x: %#13.10x\n", 21354489);
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);

	printf("=======[ft_print_X]=======\n\n");
	counter_test += ft_printf("This %%25X: %25X\n", 21354489);
	counter_oficial += printf("This %%25X: %25X\n", 21354489);
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%025X: %025X\n", 21354489);
	counter_oficial += printf("This %%025X: %025X\n", 21354489);
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%5X: %5X\n", 21354489);
	counter_oficial += printf("This %%5X: %5X\n", 21354489);
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%.5X: %.5X\n", 21354489);
	counter_oficial += printf("This %%.5X: %.5X\n", 21354489);
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%10.5X: %10.5X\n", 21354489);
	counter_oficial += printf("This %%10.5X: %10.5X\n", 21354489);
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%10.8X: %10.8X\n", 21354489);
	counter_oficial += printf("This %%10.8X: %10.8X\n", 21354489);
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%*.*X: %*.*X\n", 10, 8, 21354489);
	counter_oficial += printf("This %%*.*X: %*.*X\n", 10, 8, 21354489);
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%.X: %.X\n", 0);
	counter_oficial += printf("This %%.X: %.X\n", 0);
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%-25X: %-25X\n", 21354489);
	counter_oficial += printf("This %%-25X: %-25X\n", 21354489);
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%-5X: %-5X\n", 21354489);
	counter_oficial += printf("This %%-5X: %-5X\n", 21354489);
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%-*X: %-*X\n", 25, 21354489);
	counter_oficial += printf("This %%-*X: %-*X\n", 25, 21354489);
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%-*X: %-*X\n", -1, 21354489);
	counter_oficial += printf("This %%-*X: %-*X\n", -1, 21354489);
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%#X: %#X\n", 21354489);
	counter_oficial += printf("This %%#X: %#X\n", 21354489);
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
	counter_test += ft_printf("This %%#18.10X: %#18.10X\n", 21354489);
	counter_oficial += printf("This %%#18.10X: %#18.10X\n", 21354489);
	printf("\nResult: %i\nExpect: %i\n", counter_test, counter_oficial);
}
